Update main.py
Instance is starting... Waiting for health checks to pass.
Instance is healthy. All health checks are passing.
[X] Waiting for 4 seconds before continuing (required by "messages.EditMessage")
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 313, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/main.py", line 152, in H
    if "Done" in res: R += 1
TypeError: argument of type 'NoneType' is not iterable